### ISSUE TITLE
Can't build with Vite

### ISSUE THREAD

**Issue by OddBlueDog** [unlayer/react-email-editor#226]
When I do ```npm run build``` I get an error. I'm using Vite currently instead of CRA.

![image](https://user-images.githubusercontent.com/3959851/147818845-ce9aef5a-959c-4a19-9d2a-cb5385ace7c9.png)

**Comment by OddBlueDog** [comment]
```vite v2.7.13 building for production...
✓ 267 modules transformed.
[commonjs] Unexpected token (24:6) in C:/Users/Tom/Documents/Projects/Helpappy/frontend/node_modules/react-email-editor/src/index.js
file: C:/Users/Tom/Documents/Projects/Helpappy/frontend/node_modules/react-email-editor/src/index.js:24:6
22:
23:     return (
24:       <div
          ^
25:         style={{
26:           flex: 1,
error during build:
SyntaxError: Unexpected token (24:6) in C:/Users/Tom/Documents/Projects/Helpappy/frontend/node_modules/react-email-editor/src/index.js
    at Parser.pp$5.raise (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:19547:13)
    at Parser.pp.unexpected (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:16872:8)
    at Parser.pp$4.parseExprAtom (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:18922:10)
    at Parser.pp$4.parseExprSubscripts (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:18714:19)
    at Parser.pp$4.parseMaybeUnary (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:18680:17)
    at Parser.pp$4.parseExprOps (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:18613:19)
    at Parser.pp$4.parseMaybeConditional (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:18596:19)
    at Parser.pp$4.parseMaybeAssign (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:18564:19)
    at Parser.pp$4.parseParenAndDistinguishExpression (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:19018:28)
    at Parser.pp$4.parseExprAtom (C:\Users\Tom\Documents\Projects\Helpappy\frontend\node_modules\rollup\dist\shared\rollup.js:18881:41)```

**Comment by ayushmxn** [comment]
Recently ran into this error myself. This means your bundler doesn't understand JSX syntax. My workaround was [exposing](https://github.com/ayushmxn/react-email-editor/commit/ffc3abdda1739b9511d3255fcd1b4fb8b9c07855) the `lib` dir instead of downloading the relevant babel plugins.
